stages:
  - name: warm-up
    duration: 18
    temperature: 40
    power: 50
    fan: 0
  - name: preheat
    duration: 30
    temperature: 100
    power: 90
  - name: soak
    duration: 150
    temperature: 145
    power: 45
  - name: reflow
    duration: 60
    temperature: 215
    power: 110
  - name: dwell
    duration: 20
    temperature: 215
    power: 72
  - name: cool-1
    duration: 75
    temperature: 140
    power: 16
  - name: cool-2
    duration: 110
    temperature: 40
    power: 0
    fan: 1
  - name: cool-3
    duration: 10
    temperature: 30
    power: 0
    fan: 1