#@ displayName: Siglent SPD1305X
#@ description: Standard configuration for the Siglent SPD1305X power supply.
#@ vmax: 30
#@ imax: 5
#@ pmax: 150
###
package: Milton::Interface::SCPISingle

# The UDP6721 has RS-232 serial ports operating at 9600 baud.
# This should pick up all ports matching /dev/ttyS<number> and /dev/ttyUSB<number>
port: /dev/ttyUSB[0-9]*

# The id string should being with Siglent SPD1305X
id-pattern: ^Siglent SPD1305X

baudrate: 115200

# Sane current limits within spec
current:
  maximum: 5.0
  minimum: 0.5
  measurable: 0.1

# Sane voltage limits within spec
voltage:
  maximum: 30
  minimum: 2

# Sane power limits within spec
power:
  maximum: 149.5
  minimum: 1
